version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports: # ホストOSのポートとコンテナのポートをつなげる 
      - "8080:8080"
    tty:
      true
    volumes:
      - ./src:/go/src
    depends_on:
      - "mysql"

  mysql:
   platform: linux/x86_64
   image: mysql:8.0
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: go_database
    MYSQL_USER: go_user
    MYSQL_PASSWORD: password
    TZ: 'Asia/Tokyo'
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
    - db-data:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
    - 3306:3306
    
volumes:
  db-data:
    driver: local